title = "hsweather config"

[weather]
api = "" # api key https://darksky.net/dev
latitude = 0.0 # latitude
longitude = 0.0 # longitude

[options]
nerdfont = true # true: prints icons
round = true # true: rounds temperature
